## Another Gealine
this is  a test

In [48]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
a.shape
a.ndim


2

In [53]:
a.dtype.name

'int32'

In [55]:
a.itemsize
type(a)

numpy.ndarray

In [63]:
import numpy as np
# a = np.array([2,3,4])
# b = np.array([1.2, 3.5, 5.1])
# b.dtype
# b = np.array([(1.5, 2, 3), (4,5,6)])
# b.dtype
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [77]:
import numpy as np
from numpy import pi


# a = np.arange(24).reshape(2,3,4)
# a

a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
b**2
d = 10 * np.sin(a)
a<35





array([ True,  True, False, False])

In [85]:
import numpy as np
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
# res = A*B
# res
# res = A.dot(B)
# res
res = np.dot(A,B)
res

array([[5, 4],
       [3, 4]])

In [89]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
b += a
a += b
a

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [103]:
# a = np.ones(3, dtype=np.int32)
# b = np.linspace(0, pi, 3)
# c = a + b
# d = np.exp(c*1j)
# d.dtype.name
# a = np.random.random((2,3))
# a.sum()
# a.min()
# a.max()
b = np.arange(12).reshape(3,4)
print(b)
b.sum(axis=0)
b.min(axis=1)
b.cumsum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [6]:
import numpy as np
# indexing, slicing and iterating
a = np.arange(10)**3
print(a)
# a[2:5]
a[:6:2] = -1000
a[::-1]

[  0   1   8  27  64 125 216 343 512 729]


array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [17]:
import numpy as np
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
print(b)
# b[0:4, 0:2]
# b[:, 1]
b[-1,...]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


array([40, 41, 42, 43])

In [26]:
 c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])

# c.shape
# c[1,:, :]
# c[...,2]
# for row in b:
#     print(row)

for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [34]:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
# a.ravel()
# a.reshape(6,2)
print(a.T.shape)
print(a.shape)

(4, 3)
(3, 4)


In [39]:
# x = np.array([1, 2, 3]) + 1.5
# x.dtype.name

# a = np.array([1, 2, 3])
# a.dtype
# a[0] = 1.9
# a
# Forced casts
a = np.array([1.7, 1.2, 1.6])
b = a.astype(int)
b

array([1, 1, 1])

In [41]:
#Rounding
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
c = np.around(a).astype(int)
c

array([1, 2, 2, 2, 4, 4])

structured data types

In [52]:
# samples = np.zeros((6, ), dtype=[('sensor_code', 'S4'),
#                                     ('position', float), ('value', float)])

# samples.dtype.names
samples[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),
              ('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]
samples


array([(b'ALFA', 1. , 0.37), (b'BETA', 1. , 0.11), (b'TAU', 1. , 0.13),
       (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11), (b'TAU', 1.2, 0.13)],
      dtype=[('sensor_code', 'S4'), ('position', '<f8'), ('value', '<f8')])

Maskedarray: Dealing with propation of missing data

In [54]:
x = np.ma.array([1, 2, 3, 4], mask=[0, 1, 0, 1])
y = np.ma.array([1, 2, 3, 4], mask=[0, 1, 1, 1])
x + y

masked_array(data=[2, --, --, --],
             mask=[False,  True,  True,  True],
       fill_value=999999)

Text Files

In [55]:
%pwd

'c:\\Users\\rejalu1\\OneDrive - Henry Ford Health System\\DSC478MachineLearning'

In [68]:
data = np.loadtxt('data/populations.txt')
print(data)
data[1:20, 0:3]

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


array([[ 1901., 47200.,  6100.],
       [ 1902., 70200.,  9800.],
       [ 1903., 77400., 35200.],
       [ 1904., 36300., 59400.],
       [ 1905., 20600., 41700.],
       [ 1906., 18100., 19000.],
       [ 1907., 21400., 13000.],
       [ 1908., 22000.,  8300.],
       [ 1909., 25400.,  9100.],
       [ 1910., 27100.,  7400.],
       [ 1911., 40300.,  8000.],
       [ 1912., 57000., 12300.],
       [ 1913., 76600., 19500.],
       [ 1914., 52300., 45700.],
       [ 1915., 19500., 51100.],
       [ 1916., 11200., 29700.],
       [ 1917.,  7600., 15800.],
       [ 1918., 14600.,  9700.],
       [ 1919., 16200., 10100.]])

In [57]:
np.savetxt('data/pop2.txt', data)

Numpy's own format

In [60]:
data = np.ones((3,3))
np.save('data/pop.npy', data)
data3 = np.load('data/pop.npy')
data3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Images

In [81]:
from matplotlib import pyplot as plt
img = plt.imread('data/elephant.jpeg')
img.shape, img.dtype
# plt.imshow(img)
# plt.savefig('data/plot.png')
plt.imshow(plt.imread('data/elephant.jpeg'))


In [38]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [39]:
%pwd

'c:\\Users\\rejalu1\\OneDrive - Henry Ford Health System\\DSC450\\Assignments'

In [40]:
%ls

 Volume in drive C is Henry Ford Health System
 Volume Serial Number is 929B-D2D7

 Directory of c:\Users\rejalu1\OneDrive - Henry Ford Health System\DSC450\Assignments

09/08/2021  12:01 PM    <DIR>          .
09/08/2021  12:01 PM    <DIR>          ..
06/14/2021  08:56 PM            39,936 Assignment_Module1_.doc
08/22/2021  11:53 PM    <DIR>          FinalExamTakeHome
09/08/2021  12:01 PM               299 jnotebooktest.ipynb
08/16/2021  04:56 PM    <DIR>          MidTerm
06/14/2021  08:56 PM            11,495 Module1_SchemaExample (1).docx
08/23/2021  05:43 PM    <DIR>          Pandas
08/31/2021  05:02 PM             1,527 ReadingPSfiles.py
08/31/2021  11:41 AM    <DIR>          testFiles
06/17/2021  10:58 AM    <DIR>          Week1
06/28/2021  07:40 PM    <DIR>          Week2
07/04/2021  09:08 PM    <DIR>          Week3
07/12/2021  07:52 PM    <DIR>          Week4
08/17/2021  10:30 PM    <DIR>          Week5
08/17/2021  10:30 PM    <DIR>          Week7
08/08/2021  07:43 PM    <DIR>

In [41]:
%ls -la

 Volume in drive C is Henry Ford Health System
 Volume Serial Number is 929B-D2D7

 Directory of c:\Users\rejalu1\OneDrive - Henry Ford Health System\DSC450\Assignments



File Not Found


In [42]:
%matplotlib inline

In [43]:
%%HTML


UsageError: %%HTML is a cell magic, but the cell body is empty.


In [45]:
%%timeit
print('hi')

hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
h

KeyboardInterrupt: 

In [46]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10,5))
df

0         1         2         3         4
0 -0.834542  1.165359  2.132992 -1.119600  0.254529
1 -0.320602 -1.962570  0.371960 -0.278524  0.108181
2  0.866912  0.071812  0.298040 -0.262357 -0.396812
3  1.018893 -0.791599  1.258184  1.209569  0.006882
4 -1.343887 -1.968619 -4.082306 -0.787210 -0.683253
5  1.279594  0.176214 -2.156428 -0.676611  0.952726
6  0.116795 -0.083299 -0.301842  0.165093 -1.087457
7  1.566231  2.203652 -0.459868 -0.787441  0.449101
8 -0.750462 -0.190117 -1.294447 -0.451213  0.591984
9  0.697902 -1.226278 -0.948216  0.148238 -0.605917